# Generated by Django 3.2.9 on 2021-11-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=20)),
                ('employee_pay', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manuf_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('manuf_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('item_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=20)),
                ('item_model', models.CharField(max_length=20)),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_count', models.IntegerField()),
                ('manuf_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('order_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
                ('item_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stock')),
            ],
        ),
    ]
