# Generated by Django 3.2.9 on 2021-11-20 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='item_count',
            new_name='item_quantity',
        ),
    ]
