# Generated by Django 3.2.9 on 2021-11-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_item_count_stock_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='l_name',
            field=models.CharField(default='Last', max_length=20),
            preserve_default=False,
        ),
    ]
