# Generated by Django 3.2.9 on 2021-11-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customer_l_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='l_name',
            field=models.CharField(default='Last', max_length=20),
            preserve_default=False,
        ),
    ]
