# Generated by Django 3.2.9 on 2021-11-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20211119_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='item_ID',
            new_name='item_name',
        ),
    ]
